apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: api
type: Opaque
data:
  DB_PASSWORD: YWRtaW4=
  SECRET_API: dEo3aG90TEtJWnlXZlBEbGZLdXVtTUY4Ukt5YTBy # tJ7hotLKIZyWfPDlfKuumMF8RKya0r