apiVersion: v1
kind: Service
metadata:
  name: fastapi-lb
  namespace: api
spec:
  selector:
    app: api
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 8000       
      targetPort: 8000 
      nodePort: 30000 