apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-folder-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 500Mi
  accessModes:
    - ReadOnlyMany
  hostPath: 
    path: "/home/romain/Documents/Formation/mai24_cmlops_film/models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-folder-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Mi