apiVersion: batch/v1
kind: Job
metadata:
  name: extract-data
spec:
  template:
    spec:
      containers:
      - name: extract-data
        image: leutergmail/extract-data
        command: ["python", "main.py"]
        volumeMounts:
        - name: data-folder
          mountPath: /app/data/to_ingest
      restartPolicy: Never
      volumes:
      - name: data-folder
        hostPath: # TODO: Changer pour un format générale
          path: "/home/romain/Documents/Formation/mai24_cmlops_film/data"