apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-folder
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/romain/Documents/Formation/mai24_cmlops_film/models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-folder
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi