kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgredb
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  claimRef:
     namespace: database
     name: postgres-pvc
  hostPath:
    path: /mnt/data/postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi