{
 "title": "FastAPI Dashboard v3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler) (increase(http_requests_total{job=\"fastapi-lb\"}[1m]))",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"4xx\",job=\"fastapi-lb\"}[30s])) ",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(handler) (http_request_duration_seconds_sum{job=\"fastapi-lb\",handler!=\"none\"}) / sum by(handler) (http_request_duration_seconds_count)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(handler) (histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s])) )",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi-lb\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi-lb\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler) (increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]))\n/ sum by (handler) ( increase(http_request_duration_seconds_count[1m]) )",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(handler) ( histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  }
 ]
}