{
 "title": "Algorithme recommandation monitoring",
 "tags": [ "Model" ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Evolution of model performance ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(mur.timestamp, '60m'), \n       AVG(mur.rating) AS AVG_Rating_recommanded\nFROM \"movies_users_rating\" mur\nWHERE mur.is_recommended = True\n  AND mur.rating IS NOT NULL\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Histogram of evaluation after recommendation",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT mur.rating AS rating_after_recommandation\nFROM \"movies_users_rating\" mur\nWHERE mur.is_recommended = True\n  AND mur.rating IS NOT NULL\nand cast(mur.timestamp as date) >= current_date - interval '100' day;"
    }
   ]
  },
  {
   "title": "Rating after recommandation per kind",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT s.genre, mur.rating\nFROM   movies m\nCROSS  JOIN LATERAL string_to_table(m.genres, '|') AS s(genre)\ninner join movies_users_rating mur on m.\"movieId\" = mur.\"movieId\"\nwhere is_recommended is true \nand mur.rating is not null"
    }
   ]
  },
  {
   "title": "Comparison between films seen with and without a recommendation",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT s.genre, sum(CAST(mur.is_recommended AS INT4)) as \"movie_seen_with_reco\",\ncount(CAST(mur.is_recommended AS INT4)) as \"movie_seen_without_reco\"\nFROM   movies m\nCROSS  JOIN LATERAL string_to_table(m.genres, '|') AS s(genre)\ninner join movies_users_rating mur on m.\"movieId\" = mur.\"movieId\"\nGroup by s.genre"
    }
   ]
  },
  {
   "title": "Number of recommandation by hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(mur.timestamp, '60m'), \n       COUNT(mur.rating) AS Count_Rating_recommanded\nFROM \"movies_users_rating\" mur\nWHERE mur.is_recommended = True\n  AND mur.rating IS NOT NULL\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  }
 ]
}